version: '3.9'

services:     
  test-postgres:
    image: postgres:13.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - test-postgres:/var/lib/postgresql/data
    ports:
      - "54320:5432"

volumes:
  test-postgres: